#!/usr/bin/env python
import os
import sys
wiki_dir = "/usr/local/etc/liki/pages"

def makeDirs(directory):
    if(not os.path.exists(directory)):
        os.makedirs(directory)
    return directory

def addChild(node, term):
    return (node + "/{0}").format(term)

def getDirectory(rootdir, folder):
    return makeDirs(addChild(rootdir, folder))  

def getPage(term):
    return addChild(getDirectory(wiki_dir, term[0]), term)

def writeToFile(page, text, mode="a"):
    f = open(page, mode)
    f.write(text + "\n")
    f.close

def makeText(text, addition, message=""):
    sys.stdout.write(message)
    return text if (addition == "fin") else makeText(text + addition + "\n", raw_input())

# create page file
def createPage():
    sys.stdout.write("word: ")
    page = getPage(raw_input())
    writeToFile(page, makeText("", "", "text[type fin at EOF]: \n"))
      

# edit page file

# link page file

# list pages with key

# grep pages


createPage()
